```{r}
# Install and load the lubridate package if not already installed
if (!requireNamespace("lubridate", quietly = TRUE)) {
  install.packages("lubridate")
}
library(lubridate)
```

```{r}
# Load dataset
anillamientos <- read.csv("../limpieza/limpio/anillamiento_familia.csv")
```

```{r}
anillamientos$FechaCaptura <- as.Date(anillamientos$FechaCaptura)
anillamientos$AñoCaptura <- year(anillamientos$FechaCaptura)
anillamientos <- anillamientos[anillamientos$AñoCaptura > 1700, ]
anillamientos <- na.omit(anillamientos)

anillamientos_anillador <- anillamientos[, (names(anillamientos) %in% c("NombreAnillador", "FechaCaptura", "AñoCaptura"))]
anilladores_name_filter <- "MANUEL VAZQUEZ CASTRO"
anillamientos_anillador <- subset(anillamientos_anillador, tolower(NombreAnillador) == tolower(anilladores_name_filter))
anillamientos_anillador <- na.omit(anillamientos_anillador)

min_year <- min(anillamientos$AñoCaptura)
max_year <- max(anillamientos$AñoCaptura)

hist(anillamientos_anillador$AñoCaptura,
     xlab = "Año",
     ylab = "Frecuencia",
     main = paste(anilladores_name_filter, "capturas por año"),
     breaks = seq(min_year - 0.5, max_year + 0.5, by = 1))
```

```{r}
anillamientos_anillador <- anillamientos[, (names(anillamientos) %in% c("NombreAnillador", "FechaCaptura"))]
year_filter <- 2009
anillamientos_anillador$FechaCaptura <- as.Date(anillamientos_anillador$FechaCaptura)
anillamientos_anillador$AñoCaptura <- year(anillamientos_anillador$FechaCaptura)
anillamientos_anillador <- subset(anillamientos_anillador, AñoCaptura == year_filter)
anillamientos_anillador <- na.omit(anillamientos_anillador)

anilladores_counts <- table(anillamientos_anillador$NombreAnillador)
anilladores_counts <- anilladores_counts[order(-anilladores_counts)]
anilladores_counts <- head(anilladores_counts, 10)
anilladores_counts <- anilladores_counts[order(anilladores_counts)]
anilladores_names <- names(anilladores_counts)
colors <- rainbow(length(anilladores_counts))

max_count <- max(anilladores_counts)
xlim <- c(0, ifelse(max_count > 5000, max_count, 5000))

barplot(anilladores_counts,
      col = rev(colors),
      xlab = "Cantidad de capturas",
      main = paste("Anilladores en", year_filter),
      horiz = TRUE,
      names.arg = FALSE,
      xlim = xlim)

legend("bottomright", inset=c(0,0), legend = rev(anilladores_names), fill = colors, bg = adjustcolor("white", alpha = 0.8))
```
```{r}
anilladores_counts2 <- table(anillamientos$NombreAnillador)
anilladores_counts2 <- anilladores_counts2[order(-anilladores_counts2)]
anilladores_counts2 <- head(anilladores_counts2, 10)
anilladores_counts2 <- anilladores_counts2[order(anilladores_counts2)]
anilladores_names2 <- names(anilladores_counts2)
colors2 <- rainbow(length(anilladores_counts2))
barplot(anilladores_counts2,
      col = rev(colors2),
      xlab = "Cantidad de capturas",
      main = paste("Capturas totales por anillador"),
      horiz = TRUE,
      names.arg = FALSE,
      xlim = xlim)

legend("bottomright", inset=c(0,0), legend = rev(anilladores_names2), fill = colors2, bg = adjustcolor("white", alpha = 0.8))
```
